const fs = require('fs');

let md = fs.readFileSync('./data.md', 'utf8');

// Dictionary of exact string replacements & regex fixes
const replacements = [
  // Typography & OCR glitches
  [/ẹ/g, 'e'],
  [/ thi  trường /g, ' thị trường '],
  [/ thi  trườ /g, ' thị trường '],
  [/ thi trường /g, ' thị trường '],
  [/ thị trườn /g, ' thị trường '],
  [/ thị trườ /g, ' thị trường '],
  [/ thi trường/g, ' thị trường'],
  [/ thi trườ/g, ' thị trường'],
  [/thì trường/g, 'thị trường'],
  [/thị trường đi  nh/g, 'thị trường định'],
  [/thị trường đi nh/g, 'thị trường định'],
  [/đinh/g, 'định'],
  [/giá tri /g, 'giá trị '],
  [/giá tri/g, 'giá trị'],
  [/sử dung /g, 'sử dụng '],
  [/sử dung/g, 'sử dụng'],
  [/di  ch vu/g, 'dịch vụ'],
  [/dich vu /g, 'dịch vụ '],
  [/dich vu/g, 'dịch vụ'],
  [/phuc vu /g, 'phục vụ '],
  [/phuc vu/g, 'phục vụ'],
  [/khoa hoc /g, 'khoa học '],
  [/khoa hoc/g, 'khoa học'],
  [/quan trong /g, 'quan trọng '],
  [/quan trong/g, 'quan trọng'],
  [/muc đích /g, 'mục đích '],
  [/muc đích/g, 'mục đích'],
  [/nhiệm vu /g, 'nhiệm vụ '],
  [/nhiệm vu/g, 'nhiệm vụ'],
  [/Trồng trot/g, 'Trồng trọt'],
  [/trồng trot/g, 'trồng trọt'],
  [/Đia tô/g, 'Địa tô'],
  [/đia tô/g, 'địa tô'],
  [/đia chủ/g, 'địa chủ'],
  [/đia vị/g, 'địa vị'],
  [/đia vi/g, 'địa vị'],
  [/đia ch/g, 'địa chủ'],
  [/đia /g, 'địa '],
  [/thẹo /g, 'theo '],
  [/thẹo/g, 'theo'],
  [/Chon /g, 'Chọn '],
  [/chon /g, 'chọn '],
  [/mìn$/gm, 'mình'],
  [/mìn\n/g, 'mình\n'],
  [/mìn /g, 'mình '],
  [/côn g nhân/g, 'công nhân'],
  [/g nhân /g, 'công nhân '],
  [/g nhân\n/g, 'công nhân\n'],
  [/đẹm /g, 'đem '],
  [/xẹm /g, 'xem '],
  [/xẹm/g, 'xem'],
  [/phu thuộc/g, 'phụ thuộc'],
  [/phu  thuộc/g, 'phụ thuộc'],
  [/Ăngghẹn/g, 'Ăng-ghen'],
  [/Ăng ghẹn/g, 'Ăng-ghen'],
  [/Ăng- ghẹn/g, 'Ăng-ghen'],
  [/Ăng-ghen được/g, 'Ăng-ghen được'],
  
  // End of line truncated words
  [/phát triể\n/g, 'phát triển\n'],
  [/phát triể /g, 'phát triển '],
  [/cạnh tran\n/g, 'cạnh tranh\n'],
  [/cạnh tran /g, 'cạnh tranh '],
  [/đơn vi\n/g, 'đơn vị\n'],
  [/đơn vi /g, 'đơn vị '],
  [/đơn vi  /g, 'đơn vị '],
  [/tiền lươn\n/g, 'tiền lương\n'],
  [/tiền lươn /g, 'tiền lương '],
  [/lợi íc\n/g, 'lợi ích\n'],
  [/lợi íc /g, 'lợi ích '],
  [/2 lầ\n/g, '2 lần\n'],
  [/4 lầ\n/g, '4 lần\n'],
  [/lĩnh v\n/g, 'lĩnh vực\n'],
  [/lĩnh v /g, 'lĩnh vực '],
  [/tư nhâ\n/g, 'tư nhân\n'],
  [/tư nhâ /g, 'tư nhân '],
  [/nhà tư bả\n/g, 'nhà tư bản\n'],
  [/nhà tư bả /g, 'nhà tư bản '],
  [/hàng ho\n/g, 'hàng hóa\n'],
  [/hàng ho /g, 'hàng hóa '],
  [/đại công nghiệp tác khỏi/g, 'đại công nghiệp tách khỏi'],
  [/nộng nghiệp/g, 'nông nghiệp'],
  [/bốc lột/g, 'bóc lột'],
  [/sup đổ/g, 'sụp đổ'],
  [/tư bản sản x\n/g, 'tư bản sản xuất\n'],
  [/sản x\n/g, 'sản xuất\n'],
  [/chiu /g, 'chịu '],
  [/chiu\n/g, 'chịu\n']
];

for (let [pat, rep] of replacements) {
  md = md.replace(pat, rep);
}

fs.writeFileSync('./data.md', md, 'utf8');
console.log('Fixed spelling errors in data.md successfully!');
